name: pokedex
description: The simplest pokedex app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  dio: ^4.0.4
  shared_preferences: ^2.0.0
  get_it: ^7.2.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.2
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dependency_overrides:
#  meta: 1.3.0

dev_dependencies:

  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.0
  mockito: 5.0.6
  mobx_codegen: 2.0.2
  build_runner: 2.1.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "dev_assets/pokeapi_icon_ios.png"
  image_path_android: "dev_assets/pokeapi_icon_android.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: "dev_assets/pokeapi_splash.png"

  android_gravity: center
  ios_content_mode: center

  fullscreen: true